name: PullRequest

on:
  push:
    branches: - *
  pull_request:
    branches: - *

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Yarn
      run: yarn